package com.example.myapplication;

import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListAdapter;
import android.widget.ListView;

public class Utils {

    public static void getListViewSize(ListView myListView) {
        ListAdapter myListAdapter=myListView.getAdapter();
        if (myListAdapter==null) {
            //do nothing return null
            return;
        }
        //set listAdapter in loop for getting final size
        int totalHeight=0;
        for (int size=0; size < myListAdapter.getCount(); size++) {
            View listItem=myListAdapter.getView(size, null, myListView);
            listItem.measure(0, 0);
            totalHeight+=listItem.getMeasuredHeight();
        }
        //setting listview item in adapter
        ViewGroup.LayoutParams params=myListView.getLayoutParams();
        params.height=totalHeight + (myListView.getDividerHeight() * (myListAdapter.getCount() - 1));
        myListView.setLayoutParams(params);
        // print height of adapter on log
        Log.i("height of listItem:", String.valueOf(totalHeight));
    }
    final static String[] briefTime = new String[]{"1","2","3","4","5","6","7","8",};
    final static String[] languages = new String[]{"Abkhaz",
            "Afar",
            "Afrikaans",
            "Akan",
            "Albanian",
            "Amharic",
            "Arabic",
            "Aragonese",
            "Armenian",
            "Assamese",
            "Avaric",
            "Avestan",
            "Aymara",
            "Azerbaijani",
            "Bambara",
            "Bashkir",
            "Basque",
            "Belarusian",
            "Bengali",
            "Bihari",
            "Bislama",
            "Bosnian",
            "Breton",
            "Bulgarian",
            "Burmese",
            "Catalan",
            "Valencian",
            "Chamorro",
            "Chechen",
            "Chichewa",
            "Chewa",
            "Nyanja",
            "Chinese",
            "Chuvash",
            "Cornish",
            "Corsican",
            "Cree",
            "Croatian",
            "Czech",
            "Danish",
            "Divehi",
            "Dhivehi",
            "Maldivian",
            "Dutch",
            "English",
            "Esperanto",
            "Estonian",
            "Ewe",
            "Faroese",
            "Fijian",
            "Finnish",
            "French",
            "Fula",
            "Fulah",
            "Pulaar",
            "Pular",
            "Galician",
            "Georgian",
            "German",
            "Greek",
            "Guaran",
            "Gujarati",
            "Haitian",
            "Haitian",
            "Creole",
            "Hausa",
            "Hebrew",
            "Herero",
            "Hindi",
            "Hiri",
            "Motu",
            "Hungarian",
            "Interlingua",
            "Indonesian",
            "Interlingue",
            "Irish",
            "Igbo",
            "Inupiaq",
            "Ido",
            "Icelandic",
            "Italian",
            "Inuktitut",
            "Japanese",
            "Javanese",
            "Kalaallisut",
            "Greenlandic",
            "Kannada",
            "Kanuri",
            "Kashmiri",
            "Kazakh",
            "Khmer",
            "Kikuyu",
            "Gikuyu",
            "Kinyarwanda",
            "Kirghiz",
            "Kyrgyz",
            "Komi",
            "Kongo",
            "Korean",
            "Kurdish",
            "Kwanyama",
            "Kuanyama",
            "Latin",
            "Luxembourgish",
            "Letzeburgesch",
            "Luganda",
            "Limburgish",
            "Limburgan",
            "Limburger",
            "Lingala",
            "Lao",
            "Lithuanian",
            "Luba-Katanga",
            "Latvian",
            "Manx",
            "Macedonian",
            "Malagasy",
            "Malay",
            "Malayalam",
            "Maltese",
            "Marathi",
            "Marshallese",
            "Mongolian",
            "Nauru",
            "Navajo",
            "Navaho",
            "Norwegian",
            "Bokm",
            "North",
            "Ndebele",
            "Nepali",
            "Ndonga",
            "Norwegian",
            "Nynorsk",
            "Norwegian",
            "Nuosu",
            "South",
            "Ndebele",
            "Occitan",
            "Ojibwe",
            "Ojibwa",
            "Slavonic",
            "Bulgarian",
            "Oromo",
            "Oriya",
            "Ossetian",
            "Ossetic",
            "Panjabi",
            "Punjabi",
            "Persian",
            "Polish",
            "Pashto",
            "Pushto",
            "Portuguese",
            "Quechua",
            "Romansh",
            "Kirundi",
            "Romanian",
            "Moldavian",
            "Moldovan",
            "Russian",
            "Sanskrit",
            "Sardinian",
            "Sindhi",
            "Northern",
            "Sami",
            "Samoan",
            "Sango",
            "Serbian",
            "Scottish",
            "Gaelic",
            "Gaelic",
            "Shona",
            "Sinhala",
            "Sinhalese",
            "Slovak",
            "Slovene",
            "Somali",
            "Southern",
            "Sotho",
            "Spanish",
            "Castilian",
            "Sundanese",
            "Swahili",
            "Swati",
            "Swedish",
            "Tamil",
            "Telugu",
            "Tajik",
            "Thai",
            "Tigrinya",
            "Tibetan",
            "Turkmen",
            "Tagalog",
            "Tswana",
            "Tonga",
            "Turkish",
            "Tsonga",
            "Tatar",
            "Twi",
            "Tahitian",
            "Uighur",
            "Uyghur",
            "Ukrainian",
            "Urdu",
            "Uzbek",
            "Venda",
            "Vietnamese",
            "Volap",
            "Walloon",
            "Welsh",
            "Wolof",
            "Western",
            "Frisian",
            "Xhosa",
            "Yiddish",
            "Yoruba",
            "Zhuang",
            "Chuang"};

}
